### ISSUE TITLE
Question about freezing the T5 model parameters.

### ISSUE THREAD

**Issue by sdqdlgj** [thu-coai/CPT4DST#1]
Hi, this repo contains nice code. 
I wondering that whether the T5 model parameters are frozen during traning?
In your paper, the T5 model model parameters should be frozen, but I can not find the code that freeze the T5 model (in prompt_train.py file).
Looking forward to your reply.

**Comment by zqwerty** [comment]
Yes, they are frozen. We do not pass t5 model parameters to optimizer:
https://github.com/thu-coai/CPT4DST/blob/4b0e0e26be7ac78e303acec4ee8d684a5f8b3420/prompt_files/prompt_module.py#L111-L123

**Comment by sdqdlgj** [comment]
> 

Got it! Thanks for your quick reply 👍
